jokes = [
    'you',
    'Q: What do you call a boomerang that doesn’t work?\nA: A stick.',
    'Q: What do you call four bullfighters in quicksand?\nA: Quattro sinko.',
    'Ed: The same bike tries to run me down every day.\nFred: Sounds like a vicious cycle.',
    'Don’t interrupt someone working intently on a puzzle. Chances are, you’ll hear some crosswords.',
    'I’m a big fan of whiteboards. I find them quite re-markable.',
    'The machine at the coin factory just suddenly stopped working, with no explanation. It doesn’t make any cents!',
    'Q. What’s the difference between a hippo and a Zippo?anA. A hippo is really heavy, and a Zippo is a little lighter.',
    'All these sea monster jokes are just Kraken me up.',
    'Shout out to the people who ask what the opposite of “in” is.',
    'Q. Why can’t you run through a campground?\nA. You can only ran, because it’s past tents.',
    'Q. What sound does a sleeping T-Rex make?\nA. A dino-snore.',
    'I’m only friends with 25 letters of the alphabet. I don’t know Y.',
    'Want to hear something terrible?\nPaper.\n\n\n\n\n\nSee? I told you it was tear-able.',
    'Two windmills are standing in a wind farm. One asks, “What’s your favorite kind of music?” The other says, “I’m a big metal fan.”',
    'My boss yelled at me the other day, “You’ve got to be the worst train driver in history. How many trains did you derail last year?” I said, “Can’t say…',
    'A man sued an airline company after it lost his luggage. Sadly, he lost his case.',
    'Did you hear about the man who was accidentally buried alive?  It was a grave mistake.',
]